version: '3'

networks:
  ci:
  registry:

services:
  registry-ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 8082:80
    networks:
      - registry
    environment:
      - REGISTRY_URL=http://registry:5000
      - DELETE_IMAGES=true
  registry:
    image: registry:2
    networks:
      - registry
    ports:
      - 5000:5000
    volumes:
      - ./data/registry:/var/lib/registry
  jenkins:
    build: ./jenkins
    ports:
      - 8081:8080
    networks:
      - ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/jenkins:/var/jenkins_home
  gitlab:
    build: ./gitlab
    networks:
      - ci
    ports:
      - 8080:80
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
