version: '3'

services:
  registry-ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 8082:80
    links:
      - registry
    environment:
      - REGISTRY_URL=http://registry:5000
      - DELETE_IMAGES=true
  registry:
    image: registry:2
    volumes:
      - ./data/registry:/var/lib/registry
  jenkins:
    build: ./jenkins
    ports:
      - 8081:8080
    links:
      - registry
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/jenkins:/var/jenkins_home
  gitlab:
    build: ./gitlab
    links:
      - jenkins
    ports:
      - 8080:80
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
